name: Spectral JSON Validation CI

on: [push]

env:
  URL_SCHEMES_PATH: https://raw.githubusercontent.com/${GITHUB_REF#refs/heads/}/url-schemes
  SPECTRAL_RULESET_PATH: https://raw.githubusercontent.com/${GITHUB_REF#refs/heads/}/.spectral.yaml
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: validate JSON URL scheme
      run: |
        echo "Validating using latest stoplight/spectral using ${SPECTRAL_RULESET_PATH} on user/repo/branch ${GITHUB_REF#refs/heads/}"
        docker run stoplight/spectral lint $URL_SCHEMES_PATH/exampleUrlScheme.json -r=$SPECTRAL_RULESET_PATH --v
        docker run stoplight/spectral lint $URL_SCHEMES_PATH/feedURLscheme.json -r=$SPECTRAL_RULESET_PATH --v
        docker run stoplight/spectral lint $URL_SCHEMES_PATH/healthURLScheme.json -r=$SPECTRAL_RULESET_PATH --v
        docker run stoplight/spectral lint $URL_SCHEMES_PATH/managementURLScheme.json -r=$SPECTRAL_RULESET_PATH --v
        docker run stoplight/spectral lint $URL_SCHEMES_PATH/milkURLScheme.json -r=$SPECTRAL_RULESET_PATH --v
        docker run stoplight/spectral lint $URL_SCHEMES_PATH/performanceURLScheme.json -r=$SPECTRAL_RULESET_PATH --v
        docker run stoplight/spectral lint $URL_SCHEMES_PATH/registrationURLScheme.json -r=$SPECTRAL_RULESET_PATH --v
        docker run stoplight/spectral lint $URL_SCHEMES_PATH/reproductionURLScheme.json -r=$SPECTRAL_RULESET_PATH --v
