name: Spectral JSON Validation CI

on: [push]

env:
  URL_SCHEMES_PATH: https://raw.githubusercontent.com/${{github.repository}}/${GITHUB_REF##*/}/url-schemes
  SPECTRAL_RULESET_PATH: https://raw.githubusercontent.com/${{github.repository}}/${GITHUB_REF##*/}/.spectral.yaml
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: validate JSON URL scheme
      run: |
        docker run stoplight/spectral lint $URL_SCHEMES_PATH/exampleUrlScheme.json --r=$SPECTRAL_RULESET_PATH --v
        docker run stoplight/spectral lint $URL_SCHEMES_PATH/feedURLscheme.json --r=$SPECTRAL_RULESET_PATH --v
        docker run stoplight/spectral lint $URL_SCHEMES_PATH/healthURLScheme.json --r=$SPECTRAL_RULESET_PATH --v
        docker run stoplight/spectral lint $URL_SCHEMES_PATH/managementURLScheme.json --r=$SPECTRAL_RULESET_PATH --v
        docker run stoplight/spectral lint $URL_SCHEMES_PATH/milkURLScheme.json --r=$SPECTRAL_RULESET_PATH --v
        docker run stoplight/spectral lint $URL_SCHEMES_PATH/performanceURLScheme.json --r=$SPECTRAL_RULESET_PATH --v
        docker run stoplight/spectral lint $URL_SCHEMES_PATH/registrationURLScheme.json --r=$SPECTRAL_RULESET_PATH --v
        docker run stoplight/spectral lint $URL_SCHEMES_PATH/reproductionURLScheme.json --r=$SPECTRAL_RULESET_PATH --v
